### ISSUE TITLE
리스트 추가 요청입니다. @PenguinKKIM

### ISSUE THREAD

**Issue by devinan** [Nomad-Study/nomadstudy-github-list#52]
안녕하세요!!

노마드 스터디 1기
노마드 코더 프로필 ; https://nomadcoders.co/users/clfrck
깃 프로필 ; https://github.com/PenguinKKIM/
잘부탁드려용

_Originally posted by @PenguinKKIM in https://github.com/Nomad-Study/nomadstudy-github-list/issues/3#issuecomment-1206376416_

**Comment by devinan** [comment]
안녕하세요  🐧 님 @PenguinKKIM

Nomad Study GitHub List에 추가 요청해주셔서 감사합니다. 😎

현재 슬랙에서 동일 한 penguin 닉네임이 많아서 어느 분인지 모르겠습니다. ㅎㅎ
 Penguin Kim <--- 이 슬랙 닉네임이 맞는지 확인해주세요~

**Comment by devinan** [comment]
한국시간 8/6일 오후 10시에 최종 등록 예정입니다!

**Comment by PenguinKKIM** [comment]
넵 슬랙은 그게 맞는거같네요 !

2022년 8월 5일 (금) 오후 9:28, Devinan(SeungHyeok Lee) ***@***.***>님이
작성:
