### ISSUE TITLE
리스트 추가 요청입니다

### ISSUE THREAD

**Issue by Jaewon94** [Nomad-Study/nomadstudy-github-list#80]
**NomadCoders Profile:** _노마드코더 사이트 프로필 URL (https://nomadcoders.co/users/wodnjs3580-B7nYpr)_
**Slack Nickname:** _김재원_
**Nomad Study 기수:** _2기_

**Comment by devinan** [comment]
안녕하세요 @Jaewon94 님  한국시간 오늘 오후 10시에 master 브런치로 등록 하겠습니다.
노마드 스터디 깃헙 리스트에 추가 요청해주셔서 감사합니다.🥳

**Comment by Jaewon94** [comment]
감사합니다.
