### ISSUE TITLE
리스트 추가 요청입니다

### ISSUE THREAD

**Issue by seunga-lee** [Nomad-Study/nomadstudy-github-list#81]
**NomadCoders Profile:** _https://nomadcoders.co/users/lsa3117_
**Discord Nickname:** _승아_
**Nomad Study 기수:** _노마드 스터디 2기_

**Comment by devinan** [comment]
안녕하세요 @seunga-lee  님  한국시간 오늘 오후 10시에 master 브런치로 등록 하겠습니다.
노마드 스터디 깃헙 리스트에 추가 요청해주셔서 감사합니다.🥳
