### ISSUE TITLE
리스트 추가 요청입니다

### ISSUE THREAD

**Issue by leorivk** [Nomad-Study/nomadstudy-github-list#90]
NomadCoders Profile: https://nomadcoders.co/users/leorivk
Slack Nickname: X
Nomad Study 기수: 1기

**Comment by devinan** [comment]
@leorivk 님 내일 오후 10시반에 등록하겠습니다~

**Comment by leorivk** [comment]
추가

> @leorivk 님 내일 오후 10시반에 등록하겠습니다~
감사합니다🥲
